/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.itb.gui.progressbar;

import id.ac.itb.openie.postprocess.Postprocessor;
import id.ac.itb.openie.postprocess.PostprocessorPipeline;
import org.apache.commons.lang3.StringUtils;

import javax.swing.*;

/**
 *
 * @author elvanowen
 */
public class PostprocessorProgress extends javax.swing.JFrame {

    PostprocessorPipeline postprocessorPipeline;
    private Timer processTimer = null;
    private int tick;
    private int counter = 0;

    /**
     * Creates new form PreprocessorProgress
     */
    public PostprocessorProgress() {
        initComponents();
    }

    public PostprocessorProgress(PostprocessorPipeline postprocessorPipeline) {
        this.postprocessorPipeline = postprocessorPipeline;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        runningPostprocessorLabel = new javax.swing.JLabel();
        postprocessingDocumentsProgressLabel = new javax.swing.JLabel();
        postprocessingPipelineProgressLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        runningPostprocessorLabel.setText("Setting up postprocessors");

        showProgressLabel();

        processTimer = new javax.swing.Timer(30, e -> {
            showProgressLabel();
        });
        processTimer.start();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(runningPostprocessorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(postprocessingPipelineProgressLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(postprocessingDocumentsProgressLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runningPostprocessorLabel)
                    .addComponent(postprocessingPipelineProgressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postprocessingDocumentsProgressLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
        setTitle("Postprocessing Progress");
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostprocessorProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostprocessorProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostprocessorProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostprocessorProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostprocessorProgress().setVisible(true);
            }
        });
    }

    private void showProgressLabel() {
        counter++;
        int totalCurrentlyDocumentsPostprocessed = postprocessorPipeline.getCurrentlyPostprocessedDocuments();
        int totalDocumentsToBePostprocessed = postprocessorPipeline.getTotalDocumentsToBePostprocessed();
        String postprocessorName = "";
        String trail = StringUtils.repeat(".", tick) + StringUtils.repeat(" ", 4 - tick);

        if (counter % 10 == 0) {
            tick = (tick % 4) + 1;
        }

        if (postprocessorPipeline.getCurrentlyRunningPostprocessor() != null) {
            postprocessorName = ((Postprocessor)postprocessorPipeline.getCurrentlyRunningPostprocessor()).getPostprocessorHandler().getPluginName();
        }

        if (totalDocumentsToBePostprocessed > 0 && totalCurrentlyDocumentsPostprocessed == totalDocumentsToBePostprocessed) {
            postprocessingDocumentsProgressLabel.setText("Postprocessed Completed. Loading" + trail);
        } else {
            postprocessingDocumentsProgressLabel.setText(" " + totalCurrentlyDocumentsPostprocessed + " / " + totalDocumentsToBePostprocessed + " documents ");
        }

        updateProgressBar(totalCurrentlyDocumentsPostprocessed, totalDocumentsToBePostprocessed);

        int totalProcessedPostprocessor = postprocessorPipeline.getTotalProcessedPostprocessor();
        int totalPostprocessor = postprocessorPipeline.getNumberOfPostprocessors();

        if (postprocessorName.equalsIgnoreCase("")) {
            runningPostprocessorLabel.setText("Setting up postprocessors" + trail + StringUtils.repeat(" ", 40));
        } else {
            runningPostprocessorLabel.setText("Running " + postprocessorName + " ( " + totalProcessedPostprocessor + " / " + totalPostprocessor + " postprocessor" + (totalPostprocessor > 1 ? "s" : "") + " )");
        }
    }

    private void updateProgressBar(int numerator, int denominator) {
        jProgressBar1.setMinimum(0);
        jProgressBar1.setMaximum(denominator);
        jProgressBar1.setValue(numerator);
    }

    public void stopTimer() {
        processTimer.stop();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel postprocessingDocumentsProgressLabel;
    private javax.swing.JLabel postprocessingPipelineProgressLabel;
    private javax.swing.JLabel runningPostprocessorLabel;
    // End of variables declaration//GEN-END:variables
}
