/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.itb.gui.config;

import org.apache.commons.lang3.tuple.Pair;

import javax.swing.*;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author elvanowen
 */
public class ConfigDialog extends JFrame {

    HashMap<String, String> config;
    HashMap<String, Pair<JLabel, JTextField>> configComponents = new HashMap<>();

    public ConfigDialog(HashMap<String, String> config) {
        this.config = config;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new JButton();
        cancelButton = new JButton();

        for (Map.Entry<String, String> entry : config.entrySet()) {
            String key = entry.getKey();
            String value = entry.getValue();

            JLabel jLabel = new JLabel();
            JTextField jTextField = new JTextField();

            jLabel.setText(key);
            jTextField.setText(value);
            jTextField.setMaximumSize(new java.awt.Dimension(232, 2147483647));

            configComponents.put(key, Pair.of(jLabel, jTextField));
        }

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        okButton.setText("Save");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        GroupLayout.ParallelGroup horizontalPrlGroup = layout.createParallelGroup();

        for (Pair<JLabel, JTextField> value : configComponents.values()) {
            horizontalPrlGroup = horizontalPrlGroup.addGroup(layout.createSequentialGroup()
                    .addComponent(value.getLeft())
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(value.getRight(), GroupLayout.PREFERRED_SIZE, 332, GroupLayout.PREFERRED_SIZE));
        }

        horizontalPrlGroup
                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton));

        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(horizontalPrlGroup)
                .addContainerGap())
        );

        GroupLayout.SequentialGroup verticalSqGroup = layout.createSequentialGroup();
        verticalSqGroup.addContainerGap();

        for (Pair<JLabel, JTextField> value : configComponents.values()) {
            verticalSqGroup = verticalSqGroup.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(value.getLeft())
                    .addComponent(value.getRight(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE));
        }

        verticalSqGroup.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(okButton)
                        .addComponent(cancelButton))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);

        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(verticalSqGroup)
        );

        pack();
        setLocationRelativeTo(null);
        setTitle("Configuration");
    }// </editor-fold>//GEN-END:initComponents

        // TODO add your handling code here:
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        for (Map.Entry<String, Pair<JLabel, JTextField>> entry : configComponents.entrySet()) {
            String key = entry.getKey();
            Pair<JLabel, JTextField> value = entry.getValue();

            config.put(key, value.getRight().getText());
        }

//        System.out.println(config);

        this.dispose();

    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e){ }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigDialog(new HashMap<>()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton cancelButton;
    private JButton okButton;
    // End of variables declaration//GEN-END:variables
}
