/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.itb.gui.config;

import javax.swing.*;

/**
 *
 * @author elvanowen
 */
public class CrawlerConfig extends javax.swing.JFrame {

    id.ac.itb.openie.crawler.CrawlerConfig crawlerConfig = null;

    /**
     * Creates new form CrawlerConfig
     */
    public CrawlerConfig(id.ac.itb.openie.crawler.CrawlerConfig crawlerConfig) {
        this.crawlerConfig = crawlerConfig;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maxPagesToFetchLabel = new javax.swing.JLabel();
        maxPagesToFetchTextField = new javax.swing.JTextField();
        numberOfCrawlersLabel = new javax.swing.JLabel();
        numberOfCrawlersTextField = new javax.swing.JTextField();
        maxDepthofCrawlingLabel = new javax.swing.JLabel();
        maxDepthofCrawlingTextField = new javax.swing.JTextField();
        userAgentStringTextField = new javax.swing.JTextField();
        userAgentStringLabel = new javax.swing.JLabel();
        regexFilterPatternLabel = new javax.swing.JLabel();
        regexFilterPatternTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        maxPagesToFetchLabel.setText("Max Pages to Fetch");

        maxPagesToFetchTextField.setText(Integer.toString(crawlerConfig.getMaxPagesToFetch()));
        maxPagesToFetchTextField.setMaximumSize(new java.awt.Dimension(232, 2147483647));

        numberOfCrawlersLabel.setText("Number of Crawlers");

        numberOfCrawlersTextField.setText(Integer.toString(crawlerConfig.getNumberOfCrawlers()));
        numberOfCrawlersTextField.setMaximumSize(new java.awt.Dimension(232, 2147483647));

        maxDepthofCrawlingLabel.setText("Max Depth of Crawling");

        maxDepthofCrawlingTextField.setText(Integer.toString(crawlerConfig.getMaxDepthOfCrawling()));
        maxDepthofCrawlingTextField.setMaximumSize(new java.awt.Dimension(232, 2147483647));

        userAgentStringLabel.setText("User Agent String");

        userAgentStringTextField.setText(crawlerConfig.getUserAgentString());
        userAgentStringTextField.setMaximumSize(new java.awt.Dimension(232, 2147483647));

        regexFilterPatternLabel.setText("Regex Filter Pattern");

        regexFilterPatternTextField.setText(crawlerConfig.getFilterRegexPattern().toString());
        regexFilterPatternTextField.setMaximumSize(new java.awt.Dimension(232, 2147483647));

        okButton.setText("Save");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regexFilterPatternLabel)
                        .addGap(34, 34, 34)
                        .addComponent(regexFilterPatternTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(maxPagesToFetchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maxPagesToFetchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(numberOfCrawlersLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(numberOfCrawlersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(maxDepthofCrawlingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maxDepthofCrawlingTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(userAgentStringLabel)
                        .addGap(46, 46, 46)
                        .addComponent(userAgentStringTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxPagesToFetchLabel)
                    .addComponent(maxPagesToFetchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfCrawlersLabel)
                    .addComponent(numberOfCrawlersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxDepthofCrawlingLabel)
                    .addComponent(maxDepthofCrawlingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userAgentStringLabel)
                    .addComponent(userAgentStringTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regexFilterPatternLabel)
                    .addComponent(regexFilterPatternTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
        setTitle("Crawler Config");
    }// </editor-fold>//GEN-END:initComponents

        // TODO add your handling code here:
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        crawlerConfig.setMaxDepthOfCrawling(Integer.parseInt(maxDepthofCrawlingTextField.getText()));
        crawlerConfig.setMaxPagesToFetch(Integer.parseInt(maxPagesToFetchTextField.getText()));
        crawlerConfig.setNumberOfCrawlers(Integer.parseInt(numberOfCrawlersTextField.getText()));
        crawlerConfig.setFilterRegexPattern(regexFilterPatternTextField.getText());
        crawlerConfig.setUserAgentString(userAgentStringTextField.getText());

        this.dispose();

    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e){ }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrawlerConfig(new id.ac.itb.openie.crawler.CrawlerConfig()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel maxDepthofCrawlingLabel;
    private javax.swing.JTextField maxDepthofCrawlingTextField;
    private javax.swing.JLabel maxPagesToFetchLabel;
    private javax.swing.JTextField maxPagesToFetchTextField;
    private javax.swing.JLabel numberOfCrawlersLabel;
    private javax.swing.JTextField numberOfCrawlersTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel regexFilterPatternLabel;
    private javax.swing.JTextField regexFilterPatternTextField;
    private javax.swing.JLabel userAgentStringLabel;
    private javax.swing.JTextField userAgentStringTextField;
    // End of variables declaration//GEN-END:variables
}
