/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.itb.gui;

import id.ac.itb.gui.alert.Alert;
import id.ac.itb.gui.config.ConfigDialog;
import id.ac.itb.gui.progressbar.CrawlerProgress;
import id.ac.itb.openie.config.Config;
import id.ac.itb.openie.crawler.Crawler;
import id.ac.itb.openie.crawler.CrawlerPipeline;
import id.ac.itb.openie.crawler.ICrawlerHandler;
import id.ac.itb.openie.extractor.*;
import id.ac.itb.openie.pipeline.OpenIePipeline;
import id.ac.itb.openie.plugins.PluginLoader;
import id.ac.itb.openie.preprocess.*;
import id.ac.itb.util.UnzipUtility;
import org.apache.commons.lang3.SerializationUtils;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.Collections;

/**
 *
 * @author elvanowen
 */
public class OpenIeJFrame extends javax.swing.JFrame {

    DefaultListModel openIEPipelineListModel = new DefaultListModel();
    DefaultListModel crawlPipelineListModel = new DefaultListModel();
    DefaultListModel preprocessPipelineListModel = new DefaultListModel();
    DefaultListModel extractPipelineListModel = new DefaultListModel();
    DefaultListModel postprocessPipelineListModel = new DefaultListModel();
    PluginLoader pluginLoader = new PluginLoader();

    /**
     * Creates new form CustomizeCrawlerJFrame
     */
    public OpenIeJFrame() {
        initPlugins();
        initComponents();
    }

    private void initPlugins() {
        pluginLoader
                .registerAvailableExtensions(ICrawlerHandler.class)
                .registerAvailableExtensions(IPreprocessorHandler.class)
                .registerAvailableExtensions(IExtractorHandler.class);
    }

    private void loadPlugin() {
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try {
                String target = System.getProperty("pf4j.pluginsDir", "plugins") + File.separator + selectedFile.getName();
                File targetZip = new File(target);
                String UnzipTarget = target.replaceFirst("[.][^.]+$", "");
                Files.copy(selectedFile.toPath(), targetZip.toPath(), StandardCopyOption.REPLACE_EXISTING);

                UnzipUtility unzipUtility = new UnzipUtility();
                unzipUtility.unzip(target, UnzipTarget);
                targetZip.delete();

                new Alert("Required restarting application to load new plugins.").setVisible(true);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    private void browseStartingDirectory() {
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try {
                String target = System.getProperty("pf4j.pluginsDir", "plugins") + File.separator + selectedFile.getName();
                File targetZip = new File(target);
                String UnzipTarget = target.replaceFirst("[.][^.]+$", "");
                Files.copy(selectedFile.toPath(), targetZip.toPath(), StandardCopyOption.REPLACE_EXISTING);

                UnzipUtility unzipUtility = new UnzipUtility();
                unzipUtility.unzip(target, UnzipTarget);
                targetZip.delete();

                new Alert("Required restarting application to load new plugins.").setVisible(true);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        startingDirectoryLabel = new javax.swing.JLabel();
        browseStartingDirectoryButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        openIESectionPreprocessLabel = new javax.swing.JLabel();
        openIESectionPreprocessComboBox = new javax.swing.JComboBox<>();
        openIESectionAddPreprocessesButton = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        openIESectionExtractionLabel = new javax.swing.JLabel();
        openIESectionExtractionComboBox = new javax.swing.JComboBox<>();
        openIESectionAddExtractionButton = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        openIESectionPostprocessLabel = new javax.swing.JLabel();
        openIESectionPostprocessComboBox = new javax.swing.JComboBox<>();
        openIESectionAddPostprocessesButton = new javax.swing.JButton();
        openIESectionExecutionPipelineLabel = new javax.swing.JLabel();
        openIESectionRemovePipelineElementButton = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        openIESectionExecutePipelineElementButton = new javax.swing.JButton();
        openIESectionConfigurePipelineElementButton1 = new javax.swing.JButton();
        openIESectionCrawlerLabel = new javax.swing.JLabel();
        openIESectionCrawlerComboBox = new javax.swing.JComboBox<>();
        openIESectionAddCrawlersButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        loadCrawlerButton = new javax.swing.JButton();
        configureCrawlerButton = new javax.swing.JButton();
        crawlerComboBox = new javax.swing.JComboBox<Object>();
        runCrawlerButton = new javax.swing.JButton();
        crawlerPipelineLabel = new javax.swing.JLabel();
        addCrawlerButton = new javax.swing.JButton();
        crawlerListLabel = new javax.swing.JLabel();
        removeCrawlerButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        crawlerPipelineDragDropList = new id.ac.itb.gui.dragdroplist.DragDropList(crawlPipelineListModel);
        preprocessorPipelineDragDropList = new id.ac.itb.gui.dragdroplist.DragDropList(preprocessPipelineListModel);
        extractorPipelineDragDropList = new id.ac.itb.gui.dragdroplist.DragDropList(extractPipelineListModel);
        jPanel2 = new javax.swing.JPanel();
        preprocessorListLabel = new javax.swing.JLabel();
        preprocessorComboBox = new javax.swing.JComboBox<>();
        preprocessorPipelineLabel = new javax.swing.JLabel();
        addPreprocessorButton = new javax.swing.JButton();
        removePreprocessorButton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        loadPreprocessorButton = new javax.swing.JButton();
        configurePreprocessorButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        runPreprocessorButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        extractorListLabel = new javax.swing.JLabel();
        extractorComboBox = new javax.swing.JComboBox<>();
        extractorPipelineLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        addExtractorButton = new javax.swing.JButton();
        removeExtractorButton = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        loadExtractorButton = new javax.swing.JButton();
        configureExtractorButton = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        runExtractorButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        postprocessorListLabel = new javax.swing.JLabel();
        postprocessorComboBox = new javax.swing.JComboBox<>();
        postprocessorPipelineLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        addPostprocessorButton = new javax.swing.JButton();
        removePostprocessorButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        loadPostprocessorButton = new javax.swing.JButton();
        configurePostprocessorButton = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        runPostprocessorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadCrawlerButton.setText("Load");
        loadCrawlerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadCrawlerButtonActionPerformed(evt);
            }
        });

        startingDirectoryLabel.setText("Starting Directory");

        browseStartingDirectoryButton.setText("Browse");
        browseStartingDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseStartingDirectoryButtonActionPerformed(evt);
            }
        });

        openIESectionPreprocessLabel.setText("Preprocesses");

        openIESectionPreprocessComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(pluginLoader.getExtensions(IPreprocessorHandler.class).toArray()));

        openIESectionAddPreprocessesButton.setText("+");
        openIESectionAddPreprocessesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openIESectionAddPreprocessesButtonActionPerformed(evt);
            }
        });

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        openIESectionExtractionLabel.setText("Extraction");

        openIESectionExtractionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(pluginLoader.getExtensions(IExtractorHandler.class).toArray()));

        openIESectionAddExtractionButton.setText("+");
        openIESectionAddExtractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openIESectionAddExtractionButtonActionPerformed(evt);
            }
        });

        configureCrawlerButton.setText("Configure");
        configureCrawlerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configureCrawlerButtonActionPerformed(evt);
            }
        });

        openIESectionPostprocessLabel.setText("Postprocesses");

        openIESectionPostprocessComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        openIESectionAddPostprocessesButton.setText("+");
        openIESectionAddPostprocessesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configureCrawlerButtonActionPerformed(evt);
                openIESectionAddPostprocessesButtonActionPerformed(evt);
            }
        });

        openIESectionExecutionPipelineLabel.setText("Execution Pipeline");

        openIESectionRemovePipelineElementButton.setText("Remove");
        openIESectionRemovePipelineElementButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        openIESectionRemovePipelineElementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openIESectionRemovePipelineElementButtonActionPerformed(evt);
            }
        });
        configureCrawlerButton.setEnabled(false);

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);

        openIESectionExecutePipelineElementButton.setText("Execute");
        openIESectionExecutePipelineElementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openIESectionExecutePipelineElementButtonActionPerformed(evt);
            }
        });

        openIESectionConfigurePipelineElementButton1.setText("Configure");
        openIESectionConfigurePipelineElementButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openIESectionConfigurePipelineElementButton1ActionPerformed(evt);
            }
        });

        openIESectionCrawlerLabel.setText("Crawlers");
        openIESectionCrawlerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(pluginLoader.getExtensions(ICrawlerHandler.class).toArray()));

        openIESectionAddCrawlersButton.setText("+");
        openIESectionAddCrawlersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openIESectionAddCrawlersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(openIESectionPreprocessLabel)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(openIESectionPreprocessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(openIESectionAddPreprocessesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(openIESectionExtractionLabel)
                                                                .addGap(63, 63, 63))
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(openIESectionExtractionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(openIESectionAddExtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(openIESectionPostprocessLabel)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(openIESectionPostprocessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(openIESectionAddPostprocessesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(jSeparator3)
                                        .addComponent(jSeparator11)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(openIESectionExecutionPipelineLabel)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(openIESectionConfigurePipelineElementButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(openIESectionRemovePipelineElementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(openIESectionExecutePipelineElementButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(startingDirectoryLabel)
                                                        .addComponent(browseStartingDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(openIESectionCrawlerLabel)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(openIESectionCrawlerComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(openIESectionAddCrawlersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(startingDirectoryLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(browseStartingDirectoryButton))
                                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(openIESectionCrawlerLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(openIESectionCrawlerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(openIESectionAddCrawlersButton))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(openIESectionPreprocessLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(openIESectionPreprocessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(openIESectionAddPreprocessesButton)))
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(openIESectionExtractionLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(openIESectionExtractionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(openIESectionAddExtractionButton)))
                                                .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                .addComponent(jSeparator13))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(openIESectionPostprocessLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(openIESectionPostprocessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(openIESectionAddPostprocessesButton))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openIESectionExecutionPipelineLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(openIESectionRemovePipelineElementButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(openIESectionConfigurePipelineElementButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                                .addComponent(openIESectionExecutePipelineElementButton))
                                        .addComponent(jScrollPane6))
                                .addContainerGap())
        );

        jTabbedPane1.addTab("Open IE", jPanel5);

        runCrawlerButton.setText("Run Crawler Pipeline");
        runCrawlerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runCrawlerButtonActionPerformed(evt);
            }
        });

        crawlerPipelineLabel.setText("Crawler Pipeline");

        addCrawlerButton.setText("Add To Pipeline");
        addCrawlerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCrawlerButtonActionPerformed(evt);
            }
        });

        crawlerListLabel.setText("Crawler List");

        crawlerPipelineDragDropList.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent ev) {
                Crawler selectedCrawler = (Crawler) crawlerPipelineDragDropList.getSelectedValue();
                if (selectedCrawler != null && selectedCrawler.getCrawlerhandler().getAvailableConfigurations() != null) {
                    configureCrawlerButton.setEnabled(true);
                } else {
                    configureCrawlerButton.setEnabled(false);
                }
            }
        });

        crawlerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(pluginLoader.getExtensions(ICrawlerHandler.class).toArray()));
        // By default add File Writer to execution pipeline
        for (int i=0;i<crawlerComboBox.getItemCount(); i++) {
            ICrawlerHandler crawlerHandler = (ICrawlerHandler) pluginLoader.getExtensions(ICrawlerHandler.class).get(i);
            String pluginName = crawlerHandler.getPluginName();

            if (pluginName.equalsIgnoreCase("File Writer")) {
                Crawler crawler = new Crawler().setCrawlerhandler(crawlerHandler);
                crawlPipelineListModel.addElement(crawler);
            }
        }

        removeCrawlerButton.setText("Remove From Pipeline");
        removeCrawlerButton.setEnabled(false);
        removeCrawlerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCrawlerButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(crawlerPipelineDragDropList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(crawlerComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(crawlerListLabel)
                                                        .addComponent(crawlerPipelineLabel)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(addCrawlerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(runCrawlerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(loadCrawlerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(removeCrawlerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(configureCrawlerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jSeparator4))))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(crawlerListLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(crawlerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(crawlerPipelineLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(addCrawlerButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(removeCrawlerButton)
                                                .addGap(12, 12, 12)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(loadCrawlerButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(configureCrawlerButton)
                                                .addGap(10, 10, 10)
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(runCrawlerButton)
                                                .addGap(75, 75, 75))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1)
                                                .addContainerGap())))
        );

        jTabbedPane1.addTab("Crawl", jPanel1);

        preprocessorListLabel.setText("Preprocessor List");

        preprocessorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(pluginLoader.getExtensions(IPreprocessorHandler.class).toArray()));

        // By default add File Reader to execution pipeline
        for (int i=0;i<preprocessorComboBox.getItemCount(); i++) {
            IPreprocessorHandler preprocessorHandler = (IPreprocessorHandler) pluginLoader.getExtensions(IPreprocessorHandler.class).get(i);
            String pluginName = preprocessorHandler.getPluginName();

            if (pluginName.equalsIgnoreCase("File Reader")) {
                Preprocessor preprocessor = new Preprocessor().setPreprocessorHandler(preprocessorHandler);
                preprocessPipelineListModel.addElement(preprocessor);
            }
        }

        // By default add File Writer to execution pipeline
        for (int i=0;i<preprocessorComboBox.getItemCount(); i++) {
            IPreprocessorHandler preprocessorHandler = (IPreprocessorHandler) pluginLoader.getExtensions(IPreprocessorHandler.class).get(i);
            String pluginName = preprocessorHandler.getPluginName();

            if (pluginName.equalsIgnoreCase("File Writer")) {
                Preprocessor preprocessor = new Preprocessor().setPreprocessorHandler(preprocessorHandler);
                preprocessPipelineListModel.addElement(preprocessor);
            }
        }

        preprocessorPipelineLabel.setText("Preprocessor Pipeline");

        addPreprocessorButton.setText("Add To Pipeline");
        addPreprocessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPreprocessorButtonActionPerformed(evt);
            }
        });

        removePreprocessorButton.setText("Remove From Pipeline");
        removePreprocessorButton.setEnabled(false);
        removePreprocessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePreprocessorButtonActionPerformed(evt);
            }
        });

        loadPreprocessorButton.setText("Load");
        loadPreprocessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadPreprocessorButtonActionPerformed(evt);
            }
        });

        configurePreprocessorButton.setText("Configure");
        configurePreprocessorButton.setEnabled(false);
        crawlerPipelineDragDropList.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent ev) {
                Crawler selectedCrawler = (Crawler) crawlerPipelineDragDropList.getSelectedValue();

                if (selectedCrawler != null) {
                    if (selectedCrawler.getCrawlerhandler().getAvailableConfigurations() != null) {
                        configureCrawlerButton.setEnabled(true);
                    } else {
                        configureCrawlerButton.setEnabled(false);
                    }

                    String pluginName = selectedCrawler.getCrawlerhandler().getPluginName();
                    int nFileWriter = 0;

                    for (int i=0;i<crawlerPipelineDragDropList.getModel().getSize();i++) {
                        if (((Crawler)crawlerPipelineDragDropList.getModel().getElementAt(i)).getCrawlerhandler().getPluginName().equalsIgnoreCase("File Writer")) {
                            nFileWriter++;
                        }
                    }

                    if (pluginName.equalsIgnoreCase("File Writer")) {
                        if (nFileWriter > 1) removeCrawlerButton.setEnabled(true);
                        else removeCrawlerButton.setEnabled(false);
                    } else {
                        removeCrawlerButton.setEnabled(true);
                    }
                }
            }
        });
        preprocessorPipelineDragDropList.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent ev) {
                Preprocessor selectedPreprocessor = (Preprocessor) preprocessorPipelineDragDropList.getSelectedValue();

                if (selectedPreprocessor != null) {
                    if (selectedPreprocessor.getPreprocessorHandler().getAvailableConfigurations() != null) {
                        configurePreprocessorButton.setEnabled(true);
                    } else {
                        configurePreprocessorButton.setEnabled(false);
                    }

                    String pluginName = selectedPreprocessor.getPreprocessorHandler().getPluginName();
                    int nFileReader = 0, nFileWriter = 0;

                    for (int i=0;i<preprocessorPipelineDragDropList.getModel().getSize();i++) {
                        if (((Preprocessor)preprocessorPipelineDragDropList.getModel().getElementAt(i)).getPreprocessorHandler().getPluginName().equalsIgnoreCase("File Reader")) {
                            nFileReader++;
                        } else if (((Preprocessor)preprocessorPipelineDragDropList.getModel().getElementAt(i)).getPreprocessorHandler().getPluginName().equalsIgnoreCase("File Writer")) {
                            nFileWriter++;
                        }
                    }

                    if (pluginName.equalsIgnoreCase("File Reader")) {
                        if (nFileReader > 1) removePreprocessorButton.setEnabled(true);
                        else removePreprocessorButton.setEnabled(false);
                    }

                    if (pluginName.equalsIgnoreCase("File Writer")) {
                        if (nFileWriter > 1) removePreprocessorButton.setEnabled(true);
                        else removePreprocessorButton.setEnabled(false);
                    }
                }
            }
        });

        configurePreprocessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurePreprocessorButtonActionPerformed(evt);
            }
        });

        runPreprocessorButton.setText("Run Preprocessor Pipeline");
        runPreprocessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runPreprocessorButtonActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(preprocessorPipelineDragDropList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(preprocessorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(preprocessorListLabel)
                                                                        .addComponent(preprocessorPipelineLabel))
                                                                .addGap(277, 277, 277))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(addPreprocessorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(runPreprocessorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(loadPreprocessorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(removePreprocessorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(configurePreprocessorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jSeparator6))))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(preprocessorListLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preprocessorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preprocessorPipelineLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(addPreprocessorButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(removePreprocessorButton)
                                                .addGap(12, 12, 12)
                                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(loadPreprocessorButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(configurePreprocessorButton)
                                                .addGap(10, 10, 10)
                                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(runPreprocessorButton)
                                                .addGap(75, 75, 75))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jScrollPane5)
                                                .addContainerGap())))
        );

        jTabbedPane1.addTab("Preprocesses", jPanel2);

        extractorListLabel.setText("Extractor List");

        extractorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(pluginLoader.getExtensions(IExtractorHandler.class).toArray()));
        extractorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractorComboBoxActionPerformed(evt);
            }
        });

        extractorPipelineLabel.setText("Extractor Pipeline");

        addExtractorButton.setText("Add To Pipeline");
        addExtractorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExtractorButtonActionPerformed(evt);
            }
        });

        removeExtractorButton.setText("Remove From Pipeline");
        removeExtractorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeExtractorButtonActionPerformed(evt);
            }
        });

        loadExtractorButton.setText("Load");
        loadExtractorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadExtractorButtonActionPerformed(evt);
            }
        });

        configureExtractorButton.setText("Configure");
        configureExtractorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configureExtractorButtonActionPerformed(evt);
            }
        });

        runExtractorButton.setText("Run Extractor Pipeline");
        runExtractorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runExtractorButtonActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(extractorPipelineDragDropList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(extractorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(extractorListLabel)
                                                        .addComponent(extractorPipelineLabel)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(addExtractorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(runExtractorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(loadExtractorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(removeExtractorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(configureExtractorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jSeparator9))))
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(extractorListLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(extractorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(extractorPipelineLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(addExtractorButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(removeExtractorButton)
                                                .addGap(12, 12, 12)
                                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(loadExtractorButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(configureExtractorButton)
                                                .addGap(10, 10, 10)
                                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(runExtractorButton)
                                                .addGap(75, 75, 75))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jScrollPane4)
                                                .addContainerGap())))
        );

        jTabbedPane1.addTab("Extract", jPanel3);

        postprocessorListLabel.setText("Postprocessor List");

        postprocessorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        postprocessorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postprocessorComboBoxActionPerformed(evt);
            }
        });

        postprocessorPipelineLabel.setText("Postprocessor Pipeline");

        addPostprocessorButton.setText("Add To Pipeline");
        addPostprocessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPostprocessorButtonActionPerformed(evt);
            }
        });

        removePostprocessorButton.setText("Remove From Pipeline");
        removePostprocessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePostprocessorButtonActionPerformed(evt);
            }
        });

        loadPostprocessorButton.setText("Load");
        loadPostprocessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadPostprocessorButtonActionPerformed(evt);
            }
        });

        configurePostprocessorButton.setText("Configure");
        configurePostprocessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurePostprocessorButtonActionPerformed(evt);
            }
        });

        runPostprocessorButton.setText("Run Postprocessor Pipeline");
        runPostprocessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runPostprocessorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(postprocessorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(postprocessorListLabel)
                                                        .addComponent(postprocessorPipelineLabel)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(addPostprocessorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(runPostprocessorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(loadPostprocessorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(removePostprocessorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(configurePostprocessorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jSeparator7))))
                                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(postprocessorListLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(postprocessorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(postprocessorPipelineLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(addPostprocessorButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(removePostprocessorButton)
                                                .addGap(12, 12, 12)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(loadPostprocessorButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(configurePostprocessorButton)
                                                .addGap(10, 10, 10)
                                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(runPostprocessorButton)
                                                .addGap(75, 75, 75))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jScrollPane3)
                                                .addContainerGap())))
        );

        jTabbedPane1.addTab("Postprocesses", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
        setTitle("Open IE Bahasa Indonesia");

    }// </editor-fold>//GEN-END:initComponents

    private void configureCrawlerButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:

        Crawler selectedCrawler = (Crawler) crawlerPipelineDragDropList.getSelectedValue();

        if (selectedCrawler != null) {
            // Show configuration dialog
//            new CrawlerConfig(selectedCrawler.getCrawlerConfig()).setVisible(true);
            new ConfigDialog(selectedCrawler.getCrawlerhandler().getAvailableConfigurations()).setVisible(true);
        }

    }                                                 

    private void removeCrawlerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCrawlerButton1ActionPerformed
        // TODO add your handling code here:

        Crawler selectedCrawler = (Crawler) crawlerPipelineDragDropList.getSelectedValue();
        crawlPipelineListModel.removeElement(selectedCrawler);

    }//GEN-LAST:event_addCrawlerButton1ActionPerformed

    private void addCrawlerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCrawlerButtonActionPerformed
        // TODO add your handling code here:

        ICrawlerHandler crawlerHandler = (ICrawlerHandler) pluginLoader.getExtensions(ICrawlerHandler.class).get(crawlerComboBox.getSelectedIndex());
        Crawler crawler = new Crawler().setCrawlerhandler(SerializationUtils.clone(crawlerHandler));

        crawlPipelineListModel.add(crawlPipelineListModel.size() - 1, crawler);
//        crawlPipelineListModel.addElement(crawler);
        crawlerPipelineDragDropList.printItems();
    }//GEN-LAST:event_addCrawlerButtonActionPerformed

    private void runCrawlerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runCrawlerButtonActionPerformed
        // TODO add your handling code here:

        Crawler.clearOutputDirectory();

        for (int i = 0; i< crawlPipelineListModel.size(); i++) {
            Crawler crawler = (Crawler) crawlPipelineListModel.get(i);

            if (crawler.getCrawlerhandler().getPluginName().equalsIgnoreCase("File Writer")) {
                Crawler.addOutputDirectory(crawler.getCrawlerhandler().getAvailableConfigurations().get("Output Directory"));
            } else {
                crawlerPipeline.addCrawler(crawler);
            }
        }

        openIePipeline.clear();
        openIePipeline.addPipelineElement(crawlerPipeline);

        JFrame crawlerProgress = new CrawlerProgress(crawlerPipeline);

        SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() throws InterruptedException {
                try {
                    openIePipeline.execute();
                } catch (Exception e) {
                    e.printStackTrace();
                }

                return "";
            }

            @Override
            protected void done() {
                ((CrawlerProgress) crawlerProgress).stopTimer();
                crawlerProgress.dispose();
            }
        };

        worker.execute();
        crawlerProgress.setVisible(true);

    }//GEN-LAST:event_runCrawlerButtonActionPerformed

    private void loadCrawlerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadCrawlerButtonActionPerformed
        // TODO add your handling code here:

        loadPlugin();

    }//GEN-LAST:event_loadCrawlerButtonActionPerformed

    private void addPreprocessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPreprocessorButtonActionPerformed
        // TODO add your handling code here:

        IPreprocessorHandler preprocessorHandler = (IPreprocessorHandler) pluginLoader.getExtensions(IPreprocessorHandler.class).get(preprocessorComboBox.getSelectedIndex());
        Preprocessor preprocessor = new Preprocessor().setPreprocessorHandler(SerializationUtils.clone(preprocessorHandler));

        preprocessPipelineListModel.add(preprocessPipelineListModel.size() - 1, preprocessor);
//        preprocessPipelineListModel.addElement(preprocessor);
        preprocessorPipelineDragDropList.printItems();

    }//GEN-LAST:event_addPreprocessorButtonActionPerformed

    private void removePreprocessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePreprocessorButtonActionPerformed
        // TODO add your handling code here:

        Preprocessor selectedPreprocessor = (Preprocessor) preprocessorPipelineDragDropList.getSelectedValue();
        preprocessPipelineListModel.removeElement(selectedPreprocessor);

    }//GEN-LAST:event_removePreprocessorButtonActionPerformed

    private void loadPreprocessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadPreprocessorButtonActionPerformed
        // TODO add your handling code here:

        loadPlugin();

    }//GEN-LAST:event_loadPreprocessorButtonActionPerformed

    private void runPreprocessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runPreprocessorButtonActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i< preprocessPipelineListModel.size(); i++) {
            IPreprocessorPipelineElement preprocessorPipelineElement = (IPreprocessorPipelineElement) preprocessPipelineListModel.get(i);
            preprocessorPipeline.addPipelineElement(preprocessorPipelineElement);
        }

        openIePipeline.clear();
        openIePipeline.addPipelineElement(preprocessorPipeline);

        try {
            openIePipeline.execute();
        } catch (Exception e) {
            e.printStackTrace();
        }

//        JFrame crawlerProgress = new CrawlerProgress(crawlerPipeline);
//
//        SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
//            @Override
//            protected String doInBackground() throws InterruptedException {
//                try {
//                    openIePipeline.execute();
//                } catch (Exception e) {
//                    e.printStackTrace();
//                }
//
//                return "";
//            }
//
//            @Override
//            protected void done() {
//                ((CrawlerProgress) crawlerProgress).stopTimer();
//                crawlerProgress.dispose();
//            }
//        };
//
//        worker.execute();
//        crawlerProgress.setVisible(true);

    }//GEN-LAST:event_runPreprocessorButtonActionPerformed

    private void configurePreprocessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurePreprocessorButtonActionPerformed
        // TODO add your handling code here:

        Preprocessor selectedPreprocessor = (Preprocessor) preprocessorPipelineDragDropList.getSelectedValue();

        if (selectedPreprocessor != null) {
            // Show configuration dialog
            new ConfigDialog(selectedPreprocessor.getPreprocessorHandler().getAvailableConfigurations()).setVisible(true);
        }

    }//GEN-LAST:event_configurePreprocessorButtonActionPerformed

    private void addPostprocessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPostprocessorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPostprocessorButtonActionPerformed

    private void removePostprocessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePostprocessorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removePostprocessorButtonActionPerformed

    private void loadPostprocessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadPostprocessorButtonActionPerformed
        // TODO add your handling code here:

        loadPlugin();

    }//GEN-LAST:event_loadPostprocessorButtonActionPerformed

    private void runPostprocessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runPostprocessorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_runPostprocessorButtonActionPerformed

    private void addExtractorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExtractorButtonActionPerformed
        // TODO add your handling code here:

        IExtractorHandler extractorHandler = (IExtractorHandler) pluginLoader.getExtensions(IExtractorHandler.class).get(extractorComboBox.getSelectedIndex());

        extractPipelineListModel.addElement(extractorHandler);
        extractorPipelineDragDropList.printItems();

    }//GEN-LAST:event_addExtractorButtonActionPerformed

    private void removeExtractorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeExtractorButtonActionPerformed
        // TODO add your handling code here:

        IExtractorHandler selectedExtractorHandler = (IExtractorHandler) extractorPipelineDragDropList.getSelectedValue();
        extractPipelineListModel.removeElement(selectedExtractorHandler);

    }//GEN-LAST:event_removeExtractorButtonActionPerformed

    private void loadExtractorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadExtractorButtonActionPerformed
        // TODO add your handling code here:

        loadPlugin();

    }//GEN-LAST:event_loadExtractorButtonActionPerformed

    private void runExtractorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runExtractorButtonActionPerformed
        // TODO add your handling code here:

        extractorPipeline
                .addPipelineElement(
                        new ExtractorFileReader()
                                .setReadDirectoryPath(
                                        new Config()
                                                .getProperty("PREPROCESSES_OUTPUT_RELATIVE_PATH")));

        for (int i = 0; i< extractPipelineListModel.size(); i++) {
            IExtractorPipelineElement extractorPipelineElement = (IExtractorPipelineElement) extractPipelineListModel.get(i);
            extractorPipeline.addPipelineElement(extractorPipelineElement);
        }

        extractorPipeline
                .addPipelineElement(
                        new ExtractorFileWriter()
                                .setWriteDirectoryPath(
                                        new Config()
                                                .getProperty("EXTRACTIONS_OUTPUT_RELATIVE_PATH")));

        openIePipeline.clear();
        openIePipeline.addPipelineElement(extractorPipeline);

        try {
            openIePipeline.execute();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_runExtractorButtonActionPerformed

    private void configurePostprocessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurePostprocessorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_configurePostprocessorButtonActionPerformed

    private void postprocessorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postprocessorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postprocessorComboBoxActionPerformed

    private void configureExtractorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configureExtractorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_configureExtractorButtonActionPerformed

    private void extractorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extractorComboBoxActionPerformed

    private void browseStartingDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseStartingDirectoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_browseStartingDirectoryButtonActionPerformed

    private void openIESectionAddCrawlersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openIESectionAddCrawlersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openIESectionAddCrawlersButtonActionPerformed

    private void openIESectionAddPreprocessesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openIESectionAddPreprocessesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openIESectionAddPreprocessesButtonActionPerformed

    private void openIESectionAddExtractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openIESectionAddExtractionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openIESectionAddExtractionButtonActionPerformed

    private void openIESectionAddPostprocessesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openIESectionAddPostprocessesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openIESectionAddPostprocessesButtonActionPerformed

    private void openIESectionRemovePipelineElementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openIESectionRemovePipelineElementButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openIESectionRemovePipelineElementButtonActionPerformed

    private void openIESectionConfigurePipelineElementButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openIESectionConfigurePipelineElementButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openIESectionConfigurePipelineElementButton1ActionPerformed

    private void openIESectionExecutePipelineElementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openIESectionExecutePipelineElementButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openIESectionExecutePipelineElementButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e){ }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpenIeJFrame().setVisible(true);
            }
        });
    }

    public CrawlerPipeline getCrawlerPipeline() {
        return this.crawlerPipeline;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCrawlerButton;
    private javax.swing.JButton removeCrawlerButton;
    private javax.swing.JComboBox<Object> crawlerComboBox;
    private javax.swing.JButton addCrawlerButton1;
    private javax.swing.JButton addExtractorButton;
    private javax.swing.JButton addPostprocessorButton;
    private javax.swing.JButton addPreprocessorButton;
    private javax.swing.JButton browseStartingDirectoryButton;
    private javax.swing.JButton configureExtractorButton;
    private javax.swing.JButton configurePostprocessorButton;
    private javax.swing.JButton configurePreprocessorButton;
    private javax.swing.JLabel crawlerListLabel;
    private javax.swing.JLabel crawlerPipelineLabel;
    private javax.swing.JButton configureCrawlerButton;
    private id.ac.itb.gui.dragdroplist.DragDropList crawlerPipelineDragDropList;
    private id.ac.itb.gui.dragdroplist.DragDropList preprocessorPipelineDragDropList;
    private id.ac.itb.gui.dragdroplist.DragDropList extractorPipelineDragDropList;
    private javax.swing.JButton createCrawlerButton;
    private javax.swing.JComboBox<Object> extractorComboBox;
    private javax.swing.JLabel extractorListLabel;
    private javax.swing.JLabel extractorPipelineLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loadCrawlerButton;
    private javax.swing.JButton loadExtractorButton;
    private javax.swing.JButton loadPostprocessorButton;
    private javax.swing.JButton loadPreprocessorButton;
    private javax.swing.JComboBox<Object> postprocessorComboBox;
    private javax.swing.JButton openIESectionAddCrawlersButton;
    private javax.swing.JButton openIESectionAddExtractionButton;
    private javax.swing.JButton openIESectionAddPostprocessesButton;
    private javax.swing.JButton openIESectionAddPreprocessesButton;
    private javax.swing.JButton openIESectionConfigurePipelineElementButton1;
    private javax.swing.JComboBox<Object> openIESectionCrawlerComboBox;
    private javax.swing.JLabel openIESectionCrawlerLabel;
    private javax.swing.JButton openIESectionExecutePipelineElementButton;
    private javax.swing.JLabel openIESectionExecutionPipelineLabel;
    private javax.swing.JComboBox<Object> openIESectionExtractionComboBox;
    private javax.swing.JLabel openIESectionExtractionLabel;
    private javax.swing.JComboBox<String> openIESectionPostprocessComboBox;
    private javax.swing.JLabel openIESectionPostprocessLabel;
    private javax.swing.JComboBox<Object> openIESectionPreprocessComboBox;
    private javax.swing.JLabel openIESectionPreprocessLabel;
    private javax.swing.JButton openIESectionRemovePipelineElementButton;
    private javax.swing.JLabel postprocessorListLabel;
    private javax.swing.JLabel postprocessorPipelineLabel;
    private javax.swing.JComboBox<Object> preprocessorComboBox;
    private javax.swing.JLabel preprocessorListLabel;
    private javax.swing.JLabel preprocessorPipelineLabel;
    private javax.swing.JButton removeExtractorButton;
    private javax.swing.JButton removePostprocessorButton;
    private javax.swing.JButton removePreprocessorButton;
    private javax.swing.JButton runCrawlerButton;
    private javax.swing.JButton runExtractorButton;
    private javax.swing.JButton runPostprocessorButton;
    private javax.swing.JButton runPreprocessorButton;
    private javax.swing.JLabel startingDirectoryLabel;
    // End of variables declaration//GEN-END:variables

    private CrawlerPipeline crawlerPipeline = new CrawlerPipeline();
    private PreprocessorPipeline preprocessorPipeline = new PreprocessorPipeline();
    private ExtractorPipeline extractorPipeline = new ExtractorPipeline();
    private OpenIePipeline openIePipeline = new OpenIePipeline();
}
